# Generated by Django 6.0.7 on 2026-08-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('language', models.CharField(max_length=30)),
                ('default_test_command', models.CharField(max_length=255)),
                ('detection_file', models.CharField(help_text='File used to detect the framework (e.g. manage.py, artisan).', max_length=100)),
                ('supported', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('architecture', models.CharField(choices=[('monolith', 'Monolith'), ('microservice', 'Microservice')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('analysis_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('completed', 'Completed')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_version', models.CharField(blank=True, max_length=30)),
                ('package_manager', models.CharField(blank=True, max_length=30)),
                ('operating_system', models.CharField(max_length=50)),
                ('detected_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_profiles', to='projects.framework')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='projects.project')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
