# Generated by Django 6.1 on 2026-08-30 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_developerteam'),
        ('projects', '0002_project_connection_code_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(default='Default Integration Suite', max_length=255)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('running', 'Running'), ('error', 'Error')], default='passed', max_length=20)),
                ('command', models.CharField(default='npm test', max_length=255)),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('skipped_tests', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_test_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='projects.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='accounts.developerteam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
