# Generated by Django 6.1 on 2026-08-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_testrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
