# Generated by Django 6.1 on 2026-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_faultinjection'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='docker_containers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
