# Generated by Django 6.1 on 2026-09-23 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectprofile_docker_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultinjection',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='FaultInjectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.faultinjection')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
    ]
