# Generated by Django 6.0.7 on 2026-08-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('developer', 'Developer')], default='developer', max_length=20),
        ),
    ]
