# Generated by Django 6.1 on 2026-08-30 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
        ('projects', '0002_project_connection_code_alter_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.companyprofile')),
                ('members', models.ManyToManyField(blank=True, related_name='developer_teams', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, related_name='assigned_teams', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
