# Generated by Django 6.1 on 2026-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cleanup_legacy_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='ownership_certificate',
            field=models.TextField(blank=True, default='', help_text='Base64 or document URL for company ownership / incorporation certificate'),
        ),
    ]
